env:
  group_size: 4
  batch_size: 64
  max_batches_offpolicy: 3
  tokenizer_name: "Qwen/Qwen3-8B"
  use_wandb: true
  rollout_server_url: "http://localhost:8000"
  wandb_name: "min-business-strategy-env"
  ensure_scores_are_not_same: false
  max_token_length: 384
  max_num_workers: 16
  total_steps: 20
  steps_per_eval: 5

openai:
  - model_name: "Qwen/Qwen3-8B"
    base_url: "http://localhost:8001/v1"
    api_key: "x"
    weight: 1.0
    num_requests_for_eval: 64

tinker:
  lora_rank: 16
  learning_rate: 0.00004
  max_token_trainer_length: 512
  checkpoint_dir: "./temp/"
  save_checkpoint_interval: 0
  wandb_project: "atropos-min-business-strategy"
  wandb_group: null
  wandb_run_name: "min-business-strategy"

slurm: false
testing: false
